title: My First Week in a Bootcamp
author: Daniel G.Tamunotonye
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This is basically how my experience in the first week of my coding Bootcamp was in GA.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
